export const CHANNELS = {
    "Leeds": { name:"Leeds United", channelId : "UCyQcJHDN4uYfPa1DHzKVSnw"},
    "Arsenal":           { name: "Arsenal",             channelId: "UCpryVRk_VDudG8SHXgWcG0w" },
  // "Aston Villa":       { name: "Aston Villa",         channelId: "..." },
  "Bournemouth":       { name: "AFC Bournemouth",     channelId: "UCeOCuVSSweaEj6oVtJZEKQw" },
  // "Brentford":         { name: "Brentford FC",        channelId: "..." },
  "Brighton":          { name: "Brighton & Hove Albion",channelId: "UCf-cpC9WAdOsas19JHipukA" },
  "Chelsea":           { name: "Chelsea FC",          channelId: "UC-vYD3MIjYW-EEfBGwlsd_A" },
  // "Crystal Palace":    { name: "Crystal Palace",      channelId: "..." },
  "Everton":           { name: "Everton",             channelId: "UCtK4QAczAN2mt2ow_jlGinQ" },
  "Fulham":            { name: "Fulham FC",           channelId: "UC2VLfz92cTT8jHIFOecC-LA" },
  "Burnley":           { name: "Burnley",        channelId: "UChvUXuSDeEFSQZS8GcPMtkg" },
  "Sunderland":         { name: "Sunderland",      channelId: "UC_r3a2tv0Z4NMGIyV3HoqKg" },
  "Liverpool":         { name: "Liverpool FC",        channelId: "UC9LQwHZoucFT94I2h6JOcjw" },
  "Man City":          { name: "Manchester City",     channelId: "UCkzCjdRMrW2vXLx8mvPVLdQ" }, 
  "Man Utd":           { name: "Manchester United",   channelId: "UC6yW44UGJJBvYTlfC7CRg2Q" }, 
  "Newcastle":         { name: "Newcastle United",    channelId: "UCywGl_BPp9QhD0uAcP2HsJw" },
  "Nott'm Forest":     { name: "Nottingham Forest",   channelId: "UCyAxjuAr8f_BFDGCO3Htbxw" }, 
  "Spurs":             { name: "Tottenham Hotspur",   channelId: "UCB9aWK0xfz2P-Ny2nsXGHrA" }, 
  "West Ham":          { name: "West Ham United",     channelId: "UCCNOsmurvpEit9paBOzWtUg" },
  // "Wolves":            { name: "Wolverhampton",       channelId: "..." }
}