

FROM node:18-slim


RUN apt-get update && \
    apt-get install -y python3 python-is-python3 ffmpeg make g++ && \
    rm -rf /var/lib/apt/lists/*


WORKDIR /app

COPY package*.json ./


RUN npm ci --omit=dev


COPY . .

CMD ["node", "index.js"]