# server/nixpacks.toml

[phases.setup]
# 1. Install Node, Python 3, and FFmpeg
nixPkgs = ['nodejs', 'python3', 'ffmpeg']

[phases.install]
# 2. Create a "shortcut" so 'python' commands point to 'python3'
# 3. Then run npm install
cmds = [
    'ln -sf $(which python3) /usr/bin/python', 
    'npm ci'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'node index.js'